# Generated by Django 4.1 on 2022-09-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_P',
            new_name='nombre',
        ),
    ]
